# Generated by Django 3.0.3 on 2020-07-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
